### ISSUE TITLE
I donate to But I also do not download.

### ISSUE THREAD

**Issue by AugustKunGz** [InventivetalentDev/download.inventivetalent.org#1]
I donate to But I also do not download.
I want this plugin.

**Comment by AugustKunGz** [comment]
![image](https://cloud.githubusercontent.com/assets/7895000/22682977/62103e36-ed48-11e6-9b37-7f123d637961.png)

**Comment by InventivetalentDev** [comment]
Alright, first of all: Do you realize that you don't necessarily have to donate in order to download the plugin?  

Since this is a new system and I didn't really have a proper way to test it (It's a bit hard to donate to yourself), I don't know if it's working as intended yet. 
Theoretically, you should've been returned to the download page after you made the donation (thanks, btw :)). Let me know if it didn't work, as I said, you can just use the direct download if you want.
